Кусый Максим
kontur-courses/testing pull request #122
Opened 2020-10-23 17:24 UTC by PShenica

@hyperbodya

2020-10-25 07:43 UTC, Belianin requested changes

2020-10-25 07:43 UTC, Belianin commented on cs/HomeExercises/ObjectComparison.cs
> +					.Excluding(person => person.SelectedMemberPath.EndsWith(nameof(Person.Id)))
Почему здесь используется метод `EndsWith`?
Будет ли тест корректным, если мы добавим новое свойство `ParentId`?

2020-10-25 07:43 UTC, Belianin commented on cs/HomeExercises/NumberValidatorTests.cs
> +			}
В чем смысл проверять именно так? Почему не хватит просто пары тест-кейсов с большими числами?

2020-10-25 07:43 UTC, Belianin commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void ThrowException_When(
Лучше разделить этот метод на `ThrowException_When` и `NotThrowException_When`. Не нужно переусложнять тесты, добавляя в них витиеватую логику и дополнительные переменные.

Если у тебя упадет тест на случае с `shouldThrowException = false`, из-за названия, ты будешь думать, что у тебя не вылетело исключение, когда должно было, хотя в реальности условие противоположное.

В целом, даже количество кода сократится, если ты разнесешь его на разные методы.

2020-10-26 11:39 UTC, PShenica commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void ThrowException_When(
Согласен, ошибка с неймингом, лучше вынести в разные методы `ThrowException_When` и `NotThrowException_When`.

2020-10-26 11:44 UTC, PShenica commented on cs/HomeExercises/NumberValidatorTests.cs
> +			}
Упс, забыл убрать после рефакторинга 😄.
На самом деле особого смысла конкретно в такой проверке нет, лучше убрать `IsValidNumber_WorkFast_OnBigNumbers` и добавить `Timeout` к `IsValidNumber_ReturnResult_When` чтобы отслеживать быстроту работы метода `IsValidNumber`.

2020-10-26 11:54 UTC, PShenica commented on cs/HomeExercises/ObjectComparison.cs
> +					.Excluding(person => person.SelectedMemberPath.EndsWith(nameof(Person.Id)))
Если добавить метод `ParentId` то он тоже окажеться вне проверки персон, наверное это даже хорошо) 
- `ParentId` и так содержиться в `Parent`, это его свойство `Parent.Id`.
- Id - это уникальный признак объектов, он может быть только один такой. Значит ParentId по своей сути тоже буду уникальными и сравнивать их не надо.

---

Можно еще использовать `Contains`, тогда и `ParentId`, и `IdParent` не пройдут)) 
Только методы которые все же можно как-то логически сравнивать у персоны тоже пострадают. Например если в памяти `Parent` это один объект и id всетаки будут равны.

---

Лучше всего убедиться что именно нужное, уникальное поле `Person.Id` исключено из сравнения. 
Можно переписать сравнение следующим образом:
```C#
actualTsar.Should().BeEquivalentTo(expectedTsar, options => options
    Excluding(person => person.SelectedMemberInfo.Name.Equals(nameof(Person.Id)))
    .AllowingInfiniteRecursion());
```

Так мы точно будем уверенны что найдено искомое поле.

2020-10-26 12:08 UTC, Belianin commented on cs/HomeExercises/ObjectComparison.cs
> +					.Excluding(person => person.SelectedMemberPath.EndsWith(nameof(Person.Id)))
Ну, можно просто `==` использовать, но 'Equals` пойдет

2020-10-26 12:11 UTC, Belianin approved these changes

2022-10-26 20:06 UTC, closed without merging