Барабанова Наталья
kontur-courses/testing pull request #127
Opened 2020-10-24 10:14 UTC by NataashaBanan

@goodoldlameme

2020-10-24 18:42 UTC, goodoldlameme requested changes

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +			Assert.Throws<ArgumentException>(() => new NumberValidator(precision, scale, onlyPositive));
а можно как-то еще проверять сообщение исключения?

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +			Assert.Throws<ArgumentException>(() => new NumberValidator(precision, scale, onlyPositive));
ошибки в тексте исключения тоже можешь поменять, кстати, не уточнила, когда ты у меня это спрашивала

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(1, 2, true, TestName = "ScaleMoreThenPrecision")]
еще один кейс потерялся

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(null, TestName = "null")]
а если будут различные пустые символы?

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +
А что если все знаки будут разрешенными, но как-то не так переданы или не в том количестве?

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void CorrectWork_OnNotOnlyPositive_PrecisionThree_ScaleTwo(string checkedNumber)
название теста не очень читаемое вышло
даже не могу понять что тут проверяется

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +			var numberValidator = new NumberValidator(3, 2, false);
Вот эта информация про параметры инициализатора очень имя теста засоряет, можно сделать их частью тест кейсов

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase("-10", TestName = "TwoDigitsWithMinus")]
а если прям ооочень большое число передадут?

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase("100", TestName = "ThreeDigits")]
тут ведь смысл тест кейса совсем не в том, что тут 3 цифры

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void CorrectWork_OnNotOnlyPositive_PrecisionThree_ScaleTwo(string checkedNumber)
названия тестов и тест кейсов должны отражать смысл, а не просто словами перечислять входные параметры

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void CorrectWork_OnNotOnlyPositive_PrecisionThree_ScaleTwo(string checkedNumber)
например вот первый тест кейс(вместе с именем самого теста, имя тест кейса будет отвечать за часть про "Когда") мог бы называться IsValidNumber_ShouldValidate_WhenNoFractionPart
так сразу понятно КакойМетод_ЧтоДелает_Когда

2020-10-24 18:42 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
>  		}
совсем нет тест кейсов, которые бы проверяли, что логика валидации относительно scale и precision правильно работает, есть только случай с эксепшнами(

2020-10-25 20:22 UTC, goodoldlameme requested changes

2020-10-25 20:22 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +
я вот писала в прошлом ревью про случай, когда передают прям очень большое число, не увидела на него тест

2020-10-25 20:22 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +
также со случаями, если все знаки будут разрешенными, но как-то не так переданы или не в том количестве

2020-10-26 07:19 UTC, NataashaBanan commented on cs/HomeExercises/ObjectComparison.cs
>  			Assert.True(AreEqual(actualTsar, expectedTsar));
Если нужно проверять эквивалентность объектов, с учётом Id нельзя пользоваться этим методом. Нужно, наверно, отметить в названии, что проверка бе учёта Id.

2020-10-26 17:44 UTC, goodoldlameme requested changes

2020-10-26 17:44 UTC, goodoldlameme commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase("10000000000000000000000000000000000000000000000000000000000000000000", TestName = "BigInteger")]
в этом случае будет false не потому, что число большое, а потому, что оно содержит больше цифр, чем позволяет scale

2020-10-26 17:44 UTC, goodoldlameme commented on cs/HomeExercises/ObjectComparison.cs
> +				.Excluding(person => person.SelectedMemberPath.EndsWith("Id") ));
в правильную сторону смотришь, но что если будет поле другого типа(не Person) с таким же полем или если в тип Person добавят поле, которое будет заканчиваться на Id, а мы не хотели его исключать из сравнения?
подсказка: посмотри на SelectedMemberInfo

2020-10-26 17:44 UTC, goodoldlameme commented on cs/HomeExercises/ObjectComparison.cs
>  			Assert.True(AreEqual(actualTsar, expectedTsar));
Нет, это связанно с рекурсивностью этой функции

2020-10-27 06:26 UTC, NataashaBanan commented on cs/HomeExercises/ObjectComparison.cs
>  			Assert.True(AreEqual(actualTsar, expectedTsar));
Можно уйти в вечный цикл, при неудачных Person

2020-10-27 07:16 UTC, goodoldlameme approved these changes

2022-10-26 20:06 UTC, closed without merging