Поздняков Максим
kontur-courses/testing pull request #133
Opened 2020-10-25 12:51 UTC by CakeOrRiot

@tkirill

2020-10-26 17:48 UTC, tkirill requested changes

2020-10-26 17:48 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase("-123.100000", TestName = "Negative number with many trailing zeros")]
Хотелось проверить этим тестом, что нули не отбрасываются при подсчёте длины? Идея хорошая, разве что нулей так много, что это немного путает. Было бы понятней, если бы их было минимально необходимое количество для того, чтобы тест упал.

2020-10-26 17:48 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +        public void NumberValidator_ShouldValidateNumberWithTrailingZeroes(string input)
Если бы мне надо было по работе написать тесты на такой класс, то эти случаи я бы не стал проверять. Я ведь ясно вижу, что никакой логики по отличию одних символов от других нет, идёт работа только с длиной. Кроме регулярки, конечно.

Если бы я не видел исходного кода и тестировал класс как [чёрный ящик](https://en.wikipedia.org/wiki/Black-box_testing), тогда бы я проверил эти случаи. Предыдущий подход, кстати, называется [прозрачным ящиком](https://en.wikipedia.org/wiki/White-box_testing).

2020-10-26 17:48 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase("0,00", TestName = "Zero with comma as a delimiter")]
Тут так же — ясно видно же, что разделитель вшит в регулярку и никакой дополнительной логики нет. Значит можно проверить, что запятая работает в каком-то одном случае, а не во всех возможных.

Но если выбрать чёрный ящик, то можно проверить все варианты )

2020-10-26 17:48 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +            validator = new NumberValidator(3, 2, true);
Тут, конечно, не криминально, но вообще такая подмена, на мой взгляд, не очень хорошая. Ощущается, как небольшой костыль: вот мы во всех тестах используем один и тот же валидатор, но тут его подменим.

В более сложных тестах, где есть приватные методы, которые завязаны на поле, могут не ожидать, что валидатор подменится. Или, например, создание валиадтора могло бы быть дорогой операцией и такое создание потребляло бы лишние ресурсы. Или валидатор мог бы быть [IDisposable](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose) и тут пришлось бы звать Dispose.

Тут ничего такого нет и поэтому не особо критично, но я бы всё-таки даже тут так не сделал просто по привычке. Если хочется создавать валидатор в сетапе, то тут можно завести для него локальную переменную. Ну, или уменьшить количество тест-методов (про это есть отдельный комент), тогда было бы не так накладно создавать валидатор в них самих.

2020-10-26 17:48 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase("", TestName = "Empty string")]
`null` ещё можно проверить

2020-10-26 17:48 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase("ads13das", TestName = "String with digits inside letters")]
По-моему, даже для чёрного ящика случай "цифры в середине" выглядит уже лишним. Хотя, если ты можешь ясно объяснить его ценность, то расскажи, пожалуйста.

2020-10-26 17:48 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +        public void NumberValidator_ShouldValidateNumberWithDifferentFractionalPartDelimiters(string input)
В названиях некоторых тестов есть `_` перед `with`, а в некоторых -- нет. Надо выбрать какой-то один вариант.

2020-10-26 17:48 UTC, tkirill commented on cs/HomeExercises/ObjectComparison.cs
> +                    options => options.IncludingNestedObjects()
Разве `IncludingNestedObjects` не включено по-умолчанию?

2020-10-26 17:48 UTC, tkirill commented on cs/HomeExercises/ObjectComparison.cs
> +                .BeEquivalentTo(expectedTsar,
`BeEquivalentTo` с `Excluding` по `IMemberInfo` — то, что надо 👍

2020-10-26 17:50 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +            validator.IsValidNumber("0").Should().BeTrue();
А ты видишь какое-то преимущество в том, что есть много тест-методов, а не один или несколько, но с бОльшим количеством `[TestCase]`?

2020-10-26 17:54 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +            validator = new NumberValidator(3, 2, false);
Есть одно широко известное соглашение называть классы, которые тестируются, `sut` — system under test. В более сложных тестах, где есть и другие поля, ясно показывает что именно мы тестируем.

По запросу "system under test sut" можно найти много пруфов, я оставлю один из документации [xUnit](http://xunitpatterns.com/SUT.html).

2020-10-26 18:18 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +        public void NumberValidator_ShouldNotValidateNonNumbers(string input)
Ещё можно было бы проверить правильно ли написана регулярка — в них очень часто бывают ошибки. Например, проверить, что целая часть обязательная и ".12" не считается числом, и так далее.

2020-10-27 13:24 UTC, CakeOrRiot commented on cs/HomeExercises/ObjectComparison.cs
> +                    options => options.IncludingNestedObjects()
Проверил. Действительно, включено. Исправил

2020-10-27 13:40 UTC, CakeOrRiot commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase("", TestName = "Empty string")]
Сделано

2020-10-27 13:40 UTC, CakeOrRiot commented on cs/HomeExercises/NumberValidatorTests.cs
> +        public void NumberValidator_ShouldValidateNumberWithDifferentFractionalPartDelimiters(string input)
Исправил

2020-10-27 13:53 UTC, CakeOrRiot commented on cs/HomeExercises/NumberValidatorTests.cs
> +            validator = new NumberValidator(3, 2, true);
Понял. Мне кажется, что радикально сократить количество тестов здесь не получится (комент про тесты на ноль я учёл). Поэтому проще инициализировать в сетапе. Тем более тество со специфическим валидатором мало (5 штук и 3 из них проверяют выброс исключения).

2020-10-27 13:59 UTC, CakeOrRiot commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase("ads13das", TestName = "String with digits inside letters")]
Может регулярка не проверяет, что число начинается в начале строки и заканчивается в конце. Например так:  "([+-]?)(\d+)([.,](\d+))?". Наверное, можно либо оставить 2 теста: на число в начале и в конце, либо только 1 тест на число в середине.

2020-10-27 14:12 UTC, CakeOrRiot commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase("-123.100000", TestName = "Negative number with many trailing zeros")]
Здесь я невнимательно посмотрел на реализацию. Интуитивно кажется, что такое число должно проходить валидацию. Оказалось, что не должно. Там в теле теста я сделал просто вызвов функции без ассерта, поэтому не заметил этой ошибки.
Теперь, действительно, эти тесты не имеют смысла.

2020-10-27 14:16 UTC, CakeOrRiot commented on cs/HomeExercises/NumberValidatorTests.cs
> +        public void NumberValidator_ShouldNotValidateNonNumbers(string input)
Добавил тест

2020-10-27 14:19 UTC, CakeOrRiot commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase("0,00", TestName = "Zero with comma as a delimiter")]
Убрал лишние тесты

2020-10-27 14:51 UTC, CakeOrRiot commented on cs/HomeExercises/NumberValidatorTests.cs
> +            validator.IsValidNumber("0").Should().BeTrue();
Здесь, действительно, можно объединить в один тест с тесткейсами. В общем случае считаю, что если получается объединить тесты в метод с одним названием, то TestCase лучше. Получается меньше повторяющегося кода.

2020-10-28 09:38 UTC, tkirill approved these changes

2020-10-28 09:38 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +        private NumberValidator sutValidator;
Обычно просто `sut` называют. В этом фишка, что в какой бы тест не зашёл всегда понятно, что тестируется.

2020-10-28 09:38 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase("ads13das", TestName = "String with digits inside letters")]
Хорошо, регулярки действительно не помешает проверить тщательней.

Если честно, я бы на ревью по рабочей задаче особо не обратил на это внимание. Да, я бы сам сделал только проверку на число в начале и в конце, но дополнительный кейс с числом в середине особо ничего плохого не делает. Вот если бы лишних кейсов было много или каждый кейс был бы дорогим, тогда было бы что обсуждать.

Так что пусть будет на усмотрение автора )

2020-10-28 09:38 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +            var sutOnlyPositiveValidator = new NumberValidator(3, 2, true);
На всякий случай ещё раз повторю, что префикс `sut` это не то, что обычно делают. Обычно пишут просто `sut`.

Тут, раз `sut` уже занято, можно и так назвать, и просто без `sut` написать. Выбор будет зависеть от того, как принято в команде. В нашей команде написали бы без `sut`.

Исправлять не нужно, это просто пояснение.

2020-10-30 15:27 UTC, closed without merging