Алишер Казанцев
kontur-courses/testing pull request #136
Opened 2020-10-26 07:37 UTC by lnc0gnlt0

@tkirill

2020-10-26 18:17 UTC, tkirill requested changes

2020-10-26 18:17 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void DontThrowException_WhenPositivePrecisionAndNonNegativeScale(int precision, int scale, bool onlyPositive)
`Doesnt` и `Throws` ниже, либо `ShouldntThrow` и `ShouldThrow`. Не то, чтобы тут у всех отличный английский, просто именно эти глаголы очень часто встречаются в названиях тестов и поэтому их лучше запомнить.

2020-10-26 18:17 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void ThrowException_WhenPrecisionLessThenOrEqualToScale(int precision, int scale, bool onlyPositive)
Кажется, можно оставить один тест-метод для исключения "precision must be a non-negative number less or equal than precision", на который навесить все твои `TestCase`. Хотя, если ты видишь преимущество в том, что это именно разные методы, то расскажи, пожалуйста.

2020-10-26 18:17 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void False_WhenGivenNoneNumericString(int precision, int scale, bool onlyPositive, string value)
Здесь и в других тест-методах много `TestCase` с одинаковыми параметрами `3, 2, true` для валидатора. Это может быть сигналом о том, что эти параметры можно указать один раз при создании валиадтора в теле тест-метода, а в `TestCase` указывать только то, что действительно отличается — входную строку.

Также, в `TestCase` можно передавать и ожидаемый результат и тогда можно будет объединить тест-методы на плохие и хорошие случаи. Не то, чтобы это было чем-то кардинально лучше того, как сделано у тебя, но кода было бы меньше.

2020-10-26 18:17 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void False_WhenFractionalLengthGraterThenScale(int precision, int scale, bool onlyPositive, string value)
`Grater` -> `Greater`

2020-10-26 18:17 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(30, 10, true, "435436234714712456.128985628")]
Не понял, что этот тест проверяет такого, чего не проверяет `5, 1, true, "+110.0`?

2020-10-26 18:17 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(5, 1, true, ".")]
Отличный набор случаев на формат 👍

2020-10-26 18:17 UTC, tkirill commented on cs/HomeExercises/NumberValidatorTests.cs
> +				throw new ArgumentException("precision must be a non-negative number less or equal than precision"); // а еще тут очень странное сообщение в ошибке
Имеешь ввиду, что вместо `precision` должно быть `scale`? Да, это баг. Он случайный, молодец, что заметил!

2020-10-26 18:17 UTC, tkirill commented on cs/HomeExercises/ObjectComparison.cs
> +				options.Excluding(ctx => ctx.SelectedMemberInfo.Name.Equals("Id")));
Подход правильный.

Совсем идеально было бы использовать [nameof](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof), чтобы тест оставался рабочим, если поле `Id` переименуют.

2020-10-26 18:40 UTC, lnc0gnlt0 commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(30, 10, true, "435436234714712456.128985628")]
Второй тест проверяет, что метод может парсить целую и дробную части разделенные запятой, а не точкой
Третий проверяет случай целого числа без дробной части
Четвертый добавил на всякий случай, он проверяет корректность на условно большом числе, но в целом он лишний, да

2020-10-26 18:48 UTC, lnc0gnlt0 commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(30, 10, true, "435436234714712456.128985628")]
Первый тоже лишний

2020-10-27 11:00 UTC, tkirill approved these changes
LGTM 👍

2020-10-27 11:00 UTC, closed without merging