Арипов Сергей
kontur-courses/testing pull request #145
Opened 2021-10-27 06:34 UTC by DantesFonCake

@lamanoff

2021-10-31 08:09 UTC, lamanoff requested changes

2021-10-31 12:14 UTC, DantesFonCake commented on cs/HomeExercises/NumberValidatorTests.cs
> +            var precision = 5;
Их лучше в аргументы вынести, сделать `const int` или в аргументы конструктора напрямую прописать?

2021-10-31 12:15 UTC, DantesFonCake commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(-1, 0, "non-positive precision (\"{0}\") was provided")]
`because` лучше совсем убрать или оставить и добавить TestName?

2021-10-31 15:18 UTC, lamanoff commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(-1, 0, "non-positive precision (\"{0}\") was provided")]
Можно сделать названия такими, чтобы они говорили о том, какое поведение должно быть при проверке. Тогда `because` можно убрать.

2021-10-31 15:19 UTC, lamanoff commented on cs/HomeExercises/NumberValidatorTests.cs
> +            var precision = 5;
Можно просто сделать константами)

2021-11-01 12:46 UTC, lamanoff approved these changes

2022-10-26 20:04 UTC, closed without merging