Лялин Артем
kontur-courses/testing pull request #152
Opened 2021-10-30 10:12 UTC by ALyalin22

2021-10-30 15:28 UTC, HolyPrapor requested changes

2021-10-30 15:28 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
Не могу поставить коммент на нужную строчку, так как ты не менял там код

Опустись до кода в классе `Person`. Предлагаю подумать над тем, логично ли, что там есть какая-то публичная статическая переменная `IdCounter`, и можно ли как-то сделать лучше?

Конечно, этот код был дан, и его менять не предполагалось, но всегда полезно смотреть по сторонам.

2021-10-30 15:28 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
> +				options.Excluding(info => info.SelectedMemberInfo.Name == "Id"));
Что произойдёт, если добавить новый класс

```
class Pet{
   public int Id;
}
```

а затем в `Person` добавить его как поле?

2021-10-30 15:28 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase("-1234", 4, 2, TestName = "IntPartWithSignIsMoreThanPrecision_False", ExpectedResult = false)]
Предлагаю добавить ещё тест на краевой случай (то же самое, но precision равно 5).
Ошибки на +- единицу самые популярные :)

2021-10-30 15:28 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
>  			numberRegex = new Regex(@"^([+-]?)(\d+)([.,](\d+))?$", RegexOptions.IgnoreCase);
Предлагаю внимательно посмотреть на регулярку.
Какие случаи тесты не покрывают?

2021-10-30 15:38 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +
Не забывай форматировать код перед отправкой: удалять лишние юзинги, фиксить форматирование, etc...

2021-10-30 15:40 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
>  	public class NumberValidatorTests
И в целом мелкое замечание, которое имеет слабое отношение конкретно к этой домашке.

Почти всегда лучше придерживаться композиции 1 класс - 1 файл.
По классам и иерархии легче читать, и быстрее искать нужную инфу в проекте.

А сами тесты обычно вообще выносят в отдельную сборку, чтобы случайно не зареференсить какой-то класс, созданный чисто для тестов, и тем более чтобы они не торчали наружу, если кто-то подключает твой код как библиотеку.

2021-10-30 15:41 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
>  	public class NumberValidatorTests
Можешь разделить, можешь не делить, здесь это не так критично, но в будущих домашках обращай на это внимание

2021-10-30 18:00 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
>  			var expectedTsar = new Person("Ivan IV The Terrible", 54, 170, 70,
Кстати, категорию-то можно убрать, отрефакторили ведь! :)

2021-11-01 15:03 UTC, ALyalin22 commented on cs/HomeExercises/NumberValidatorTests.cs
>  			numberRegex = new Regex(@"^([+-]?)(\d+)([.,](\d+))?$", RegexOptions.IgnoreCase);
Добавил тест, где в числе используется запятая. Других случаев не нашёл.

2021-11-01 15:11 UTC, ALyalin22 commented on cs/HomeExercises/ObjectComparison.cs
> +				options.Excluding(info => info.SelectedMemberInfo.Name == "Id"));
В таком случае при сравнении поле Id также не будет учитываться. 
Чтобы этого не происходило добавил ещё одну проверку.

2021-11-01 15:14 UTC, ALyalin22 commented on cs/HomeExercises/ObjectComparison.cs
Исправил на приватное поле.

2021-11-01 15:23 UTC, HolyPrapor approved these changes
LGTM.
Great job!

2022-10-26 20:04 UTC, closed without merging