Тебайкин Максим
kontur-courses/testing pull request #153
Opened 2021-10-30 11:00 UTC by gODeaLoAple

@HenrickBolender

2021-10-30 15:11 UTC, HenrickBolender requested changes

2021-10-30 15:11 UTC, HenrickBolender commented on cs/HomeExercises/NumberValidatorTests.cs
> +    public class NumberValidatorTests
Ещё идеи для тестов:

* Цифры могут быть не только арабскими
* Что если алгоритм валидации поменяется и он будет проверять 1 час?
* А если я просто знак `+-` передам?

2021-10-30 15:11 UTC, HenrickBolender commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(3, 1, true, "+0.0", Description = "Signed fractional number with dot (+)")]
По сути этот тест - объединение тестов на дробную часть и знаки `+-`. Если развалятся они, то развалится и этот тест. Тогда зачем он нужен? Я бы подсократил его и подобные ниже.

2021-10-30 15:11 UTC, HenrickBolender commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(3, 2, false, " ", Description = "Get white space")]
Тоже, как будто лишний тест, какой-то особый сценарий он не проверяет.

2021-10-30 15:28 UTC, gODeaLoAple commented on cs/HomeExercises/NumberValidatorTests.cs
> +
А, да, он вроде группирует по проектам (по первому слову в namespace). Это плохо?

2021-10-30 15:58 UTC, HenrickBolender commented on cs/HomeExercises/NumberValidatorTests.cs
> +
Впервые вижу, чтобы так делали. Скорее всего, в рабочих проектах тебя так же попросят их не ставить, так что давай уберём)

2021-10-30 16:08 UTC, gODeaLoAple commented on cs/HomeExercises/ObjectComparison.cs
> +                .Excluding(x => ParentRecursiveIdMatch.IsMatch(x.SelectedMemberPath)));
Была идея просто использовать SelectedMemberInfo.Name == "Id", но тогда это правило распространится и на другие классы, содержащие поле Id. Тогда можно проверять еще и на тип, но это выглядит избыточным. К сожалению, почему-то просто написать x => x.Id не выходит - исключается Id только первого рассматриваемого царя. 
При поиске более адекватного способа проверки пошел на [stackoverflow](https://stackoverflow.com/questions/58619774/fluents-assertions-exclude-field-recursively), где нашел подозрительно похожую структуру :))) 
Там один из комментаторов пишет, что регексп это один из лучших вариантов вроде. Не знаю, мб я что-то упускаю, но пока есть 2 варианта, свободные от захардкоженных имен, но оба не выглядят просто и лаконично. Представлю их на скрине ниже
![image](https://user-images.githubusercontent.com/55148949/139540672-9615583d-5c96-4a33-b2d8-04df4b5a655d.png)
Можно ли лучше?

2021-10-30 16:09 UTC, gODeaLoAple commented on cs/HomeExercises/NumberValidatorTests.cs
> +
Без проблем.

2021-10-30 16:15 UTC, gODeaLoAple commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(3, 2, false, " ", Description = "Get white space")]
Все три TestCase или оставить хотя бы null-check? Выглядит вполне логично

2021-10-31 10:42 UTC, HenrickBolender commented on cs/HomeExercises/ObjectComparison.cs
> +                .Excluding(x => ParentRecursiveIdMatch.IsMatch(x.SelectedMemberPath)));
У твоего регекса я вижу следующие проблемы:

1) Он торчит статическим полем снаружи теста. Лучше изолировать и использовать его ровно в том месте (тесте), где он нужен.
2) Вся эта проверка с регексом - довольно сложная штука, если не знать как строится `SelectedMemberPath`. Хочется избавиться от лишнего контекста. 

Попробуй учесть это

2021-10-31 10:54 UTC, HenrickBolender commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(3, 2, false, " ", Description = "Get white space")]
null-check норм.

Вообще этот и комментарий выше - про желание сократить кол-во тестов, проверяющих примерно одно и то же.  По сути у тебя уже есть тест cо строкой `asd` - он про то, что мы кидаем валидатору символы, не являющиеся цифрами. С пробелом то же самое выходит.

2021-11-01 09:13 UTC, HenrickBolender commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(20, 0, false, "IVXLCDM", TestName = "Roman numerals used")]
Ещё бывают цирфы бирманский и тамильские, и валидироваться они должны. Возможно, мне стоило сразу упомянуть, что такие бывают, так как самому до этого догадаться трудно.

2021-11-01 09:16 UTC, HenrickBolender commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(3, 2, false, "a.sd", TestName = "Not a number with dot")]
лучше бы оставил `asd` (невалидная строка), а не `as.d` (невалидная строка _с точкой_)

2021-11-02 10:10 UTC, HenrickBolender approved these changes

2022-10-26 20:04 UTC, closed without merging