HomeWork
kontur-courses/testing pull request #154
Opened 2021-10-30 11:22 UTC by PavelLediankin

@Leoltron

2021-10-30 18:19 UTC, Leoltron requested changes

2021-10-30 18:19 UTC, Leoltron commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void Precision_ShouldBeNotNegative_AndLessThanPrecision(int scale)
Стоило бы добавить случай с `scale` больше 6

2021-10-30 18:25 UTC, Leoltron commented
Непосредственно к ревью не относится - в твоём коде смешаны отступы табуляцией и пробелами. IDE, может, и разберется, а вот гитхаб корявит отображение отступов. Советую использовать функцию решарпера Reformat Code для  соблюдения консистентности в отступах.

2021-10-31 08:28 UTC, PavelLediankin commented on cs/HomeExercises/ObjectComparison.cs
> +				actualValue.Should().Be(expectedValue);
Кажется понял что нужно сделать по аналогии с примером из презентации:
сравнить через BeEquivalentTo с опциями

2021-10-31 08:29 UTC, PavelLediankin commented on cs/HomeExercises/NumberValidatorTests.cs
> +
Да я сейчас проверил можно спокойно вызывать конструктор, но почему то когда я это делал у меня не получилось, может где-то ошибся, так что исправлю.

2021-10-31 08:32 UTC, PavelLediankin commented on cs/HomeExercises/NumberValidatorTests.cs
> +				.Should().Throw<ArgumentException>();
Вообще мне казалось что раз практика нацелена больше на FluentAssertion`s, но если нет то действительно немного удобнее писать Assert...

2021-10-31 08:33 UTC, PavelLediankin commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void OnlyPositiveValidator_SholdNotValidateNegative()
Увидел

2021-10-31 08:36 UTC, PavelLediankin commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void NotOnlyPositiveValidator_SholdValidatePosAndNeg(string number)
Вообще согласен, но 
1) При валидации чисел, PosAndNe, сложно представить как что-то кроме +/-, тем более что есть другие тесты с полным названием
2)Название и так длинновато, можно конечно разбить его на две строчки, но при запуске тестов оно будет не слишком читаемо.

2021-10-31 08:42 UTC, PavelLediankin commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void Precision_ShouldBeNotNegative_AndLessThanPrecision(int scale)
На мой взгляд это уже лишнее:
 scale  <= precision. и если  scale  == precision, как граничный случай вызывает исключение то проверять большие значения не обязательно.
 А если предположить что исключение бросается только при  scale  == precision, то можно предположить что оно бросается и при scale  =precision +1, +2,+3...+N.
 Так что действительно ли это нужно?

2021-10-31 08:44 UTC, PavelLediankin commented
> Непосредственно к ревью не относится - в твоём коде смешаны отступы табуляцией и пробелами. IDE, может, и разберется, а вот гитхаб корявит отображение отступов. Советую использовать функцию решарпера Reformat Code для соблюдения консистентности в отступах.

Насколько я знаю решарпер платный, а бесплатная версия только месяц, так что я им не пользуюсь.
Может в студии есть какой-то способ привести отступы к одному виду?

2021-10-31 12:02 UTC, Leoltron commented
> Насколько я знаю решарпер платный,

Студенты могут получить [бесплатную лицензию на все продукты JetBrains](https://www.jetbrains.com/ru-ru/community/education/#students) на время обучения напрямую или как часть [пакета продуктов GitHub](https://education.github.com/pack) для студентов

2021-10-31 12:07 UTC, Leoltron commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void Precision_ShouldBeNotNegative_AndLessThanPrecision(int scale)
Предположить можно, но стоит ли, если тесты должны давать четкую четкую картину, при каких данных код работает, а при каких - нет? Пограничные случаи стоит проверять отдельно от общего правила.

2021-10-31 12:55 UTC, Leoltron commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void NotOnlyPositiveValidator_SholdValidatePosAndNeg(string number)
Как вариант, можно применить `AnyNumber`, если уж прибегаем к использование в контексте других тестов.

2021-10-31 13:35 UTC, Leoltron commented on cs/HomeExercises/ObjectComparison.cs
> +			var ignoredFields = new string[] { "Id", "IdCounter" };
Игнор IdCounter тут не нужен, FluentAssertions пропускает статические поля классов

2021-10-31 13:40 UTC, Leoltron commented on cs/HomeExercises/ObjectComparison.cs
> +			var ignoredFields = new string[] { "Id", "IdCounter" };
"Id" можно заменить на nameof(Person.Id), так будет легче рефакторить

2021-10-31 13:41 UTC, Leoltron commented on cs/HomeExercises/ObjectComparison.cs
> +			var ignoredFields = new string[] { "Id", "IdCounter" };
Это все мелкие помарки, их необязательно править

2021-10-31 13:51 UTC, Leoltron commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void NotOnlyPositiveValidator_ShouldValidatePosAndNeg(string number)
Запятая - тоже валидный разделитель в числе

2022-10-26 20:04 UTC, closed without merging