Алемасцев Никита
kontur-courses/testing pull request #156
Opened 2021-10-30 13:39 UTC by nikovOne

2021-10-30 13:44 UTC, nikovOne commented
@orange-bird

2021-10-31 08:24 UTC, orange-bird requested changes

2021-10-31 08:24 UTC, orange-bird commented on cs/HomeExercises/NumberValidatorTests.cs
> +		//Не знаю, как будет лучше: первый тест или остальные. Конечно, выглядят  они некрасиво, зато информативнее некуда
Лучше разделять тесты логически. Так удобнее при последующей поддержке. Перечисление аргументов - это информативно, но для стороннего человека ничего не говорит. Попробуй выразить названия тестов словами без конкретных значений. Эти названия как раз и будут названиями разных типов тестов.

2021-10-31 08:24 UTC, orange-bird commented on cs/HomeExercises/NumberValidatorTests.cs
> +			Assert.Throws<ArgumentException>(() => new NumberValidator(-1));
Лучше это выражать через TestCase. Перечисление разных вариантов в контексте одного теста - неудобно. У всех test-фреймворков есть возможность передавать в один и тот же тест разные варианты значений - и это не просто так)

2021-10-31 08:24 UTC, orange-bird commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void ConstructorShouldThrowExceptionWhenPrecisionPositive()
Название теста неправильное. Как минимум - не соответствует содержанию.

2021-10-31 08:24 UTC, orange-bird commented on cs/HomeExercises/NumberValidatorTests.cs
>  	public class NumberValidatorTests
Не увидел теста на все варианты ошибок при создании `NumberValidator`.
И еще советую посмотреть его конструктор еще раз - там есть нюансы...

2021-10-31 08:24 UTC, orange-bird commented on cs/HomeExercises/ObjectComparison.cs
> +			// Не работает(((
Почему не работает? Что с ним не так?
Направление правильное. Нужно только понять, как исключить свойство, не требующее сравнения ([подсказка](https://fluentassertions.com/objectgraphs/#selecting-members)). Плюс подумать над нюансами - скажем, что будет при рекурсии (глубины 10 и больше).

2021-10-31 08:24 UTC, orange-bird commented on cs/HomeExercises/ObjectComparison.cs
> +		private static bool TsarEquals(IReflect type, Person? actual, Person? expected, ICollection<string> propertiesDontCompare)
Не нужно тут придумывать свою реализацию `BeEquivalentTo` :)
Стремление сделать велосипед - это хорошо, позволяет понять, как это работает внутри. Но простые штуки лучше просто использовать.

2021-10-31 08:24 UTC, orange-bird commented on cs/HomeExercises/ObjectComparison.cs
> +using System.Linq;
Неиспользуемые using лучше удалять.

2021-10-31 08:26 UTC, orange-bird commented on cs/HomeExercises/ObjectComparison.cs
> +			// Если не дописать, то разные значения новых полей будут проходить тест, чего быть не должно
А еще? Например, как понять, в каком месте сравнение сломалось?

2021-10-31 08:33 UTC, orange-bird commented
Еще из общего: лучше класс-реализацию отделять от класса с тестами в разные файлы. В идеале это, наверное, вообще будут разные проекты, но тут это лишнее.

2021-10-31 11:30 UTC, orange-bird commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(3, 2, true, "a.sd")]
Лучше каждому TestCase прописывать свое сообщение об ошибке, чтобы было понятно, что именно не так без необходимости смотреть на набор переменных.
К примеру, "a.sd" - очевидно, не число вообще. А ".1" - неправильный формат.

2021-10-31 11:31 UTC, orange-bird commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(3, 2, true, "-0.00")]
В чем тут с точки зрения названия теста разница между -0.00 и +0.00? Вариации теста не должны повторять друг друга.

2021-10-31 11:32 UTC, orange-bird commented on cs/HomeExercises/TsarRegistry.cs
> +﻿namespace HomeExercises
Этот класс специфичен для теста. В принципе, можно было оставить его в файле с тестом. Но можно и так.

2021-10-31 11:39 UTC, orange-bird commented on cs/HomeExercises/ObjectComparison.cs
> +				config => config.Excluding(p => Regex.IsMatch(p.SelectedMemberPath, @"^(Parent\.)*Id$")));
Не-не-не. Все гораздо проще. Прочитай документацию по ссылке, которую я оставлял.

2021-10-31 11:40 UTC, orange-bird reviewed
Движемся в правильном направлении :)

2021-10-31 11:40 UTC, nikovOne commented on cs/HomeExercises/ObjectComparison.cs
> +				config => config.Excluding(p => Regex.IsMatch(p.SelectedMemberPath, @"^(Parent\.)*Id$")));
EndsWith? Я читал, что это сравнение строк, так что какой-нибудь другой айдишник тоже отлететь может

2021-10-31 11:56 UTC, orange-bird commented on cs/HomeExercises/ObjectComparison.cs
> +				config => config.Excluding(p => Regex.IsMatch(p.SelectedMemberPath, @"^(Parent\.)*Id$")));
Да, `EndsWith` тоже не вариант по этой же причине.

2021-10-31 13:38 UTC, nikovOne commented
@orange-bird

2021-10-31 16:28 UTC, orange-bird commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(4, 2, false, "-1.23", TestName = "Should be true when input is correct")]
Если название кейса одинаковое, то проще его вообще не писать. Нет смысла. В данном тесте идеально бы было разграничить по сценариям, которые подходят.
И еще момент: нет смысла передавать precision и scale, если от них ничего не зависит и в этом тесте не проверяется их поведение.

2021-10-31 16:31 UTC, orange-bird commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(0, TestName = "Should be false when precision non positive")]
Тут маленькое замечание по названию и раз мы привыкаем писать на английском, то...
Should be false implies that we should get the result of false. But this test expects the exception to be thrown, not a specific result.
Если нужен перевод, я добавлю ;)

2021-10-31 16:36 UTC, orange-bird commented on cs/HomeExercises/ObjectComparison.cs
> +						p.SelectedMemberInfo.Name == nameof(expectedTsar.Id) && p.SelectedMemberInfo.MemberType == typeof(int)));
Работает. Почти )
Представь класс в котором есть поле `Id` типа `int`. Теперь представь его как свойство в объекте типа `Person`. Оно будет игнорироваться, а не должно. Фильтр не должен быть по типу свойства. Он должен быть по типу ______ _______ (подставь правильное :)).

2021-11-02 14:26 UTC, orange-bird approved these changes

2022-10-26 20:04 UTC, closed without merging