Максим Паньшин
kontur-courses/testing pull request #157
Opened 2021-10-30 16:31 UTC by makspanshin

2021-10-30 17:57 UTC, HolyPrapor requested changes

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
Не могу поставить коммент на нужную строчку, так как ты не менял там код

Опустись до кода в классе `Person`. Предлагаю подумать над тем, логично ли, что там есть какая-то публичная статическая переменная `IdCounter`, и можно ли как-то сделать лучше?

Конечно, этот код был дан, и его менять не предполагалось, но всегда полезно смотреть по сторонам.

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
> +			actualTsar.Should().BeEquivalentTo(expectedTsar, options => options.AllowingInfiniteRecursion()
А для чего разрешена бесконечная рекурсия?

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
> +				.Excluding(member => member.SelectedMemberInfo.Name == "Id"));
Что произойдёт, если добавить новый класс

```
class Pet{
   public int Id;
}
```

а затем в `Person` добавить его как поле?

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
>  		[Category("ToRefactor")]
Наверное, категорию можно убрать :)

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		/*
Не оставляй закомментированный код в пулл реквестах.
А ещё не забывай применять форматирование. Райдер, например, умеет делать `Code Cleanup`.

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		/*
Понятно, что это не относится к текущему случаю (мне так даже проверять удобнее :) ), но когда видишь задокументированный код в реальном проекте, всегда возникают вопросы: 
А почему он тут остался? 
А точно ли он не нужен?
В общем, лучше так не делать

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void InitNumberValidator_WhenPrecisionThrow(int precision, int scale, bool onlyPositive)
Имя теста сформируется как `NumberValidatorTests.InitNumberValidator_WhenPrecisionThrow_Precision Is Negative`. 
Я бы стремился к чему-нибудь вроде `NumberValidatorTests.Init_ThrowWhen.<TestName>`
Но необязательно брать прямо мой паттерн, попробуй просто избавиться от дублирования в названии.

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +				.WithMessage("precision must be a positive number");
А есть смысл жёстко фиксировать сообщение из эксепшена?

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[Test]
Лишний аттрибут, достаточно просто `[TestCase]` оставить.
У тебя так везде, поправишь?

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void InitNumberValidator_Сorrectly(int precision, int scale, bool onlyPositive)
Вот тут нейминг прям сложный.

Представь, что ты впервые скачал репозиторий, прогнал тесты, и у тебя упало что-то вроде `NumberValidatorTests.InitNumberValidator_Correctly.InitNumberValidator is OK`. 
Я вот из названия совсем ничего не понимаю :(
Кроме того, тут ещё и 2 раза задублировалось название класса.

Вместо `InitNumberValidator is OK` можно написать что-то вроде `Usual parameters`, имея в виду, что это не какой-то крайний случай, а обычное "стандартное" использование.

Кстати, есть подозрение, что эти тесты неявно "проходятся" во время тестов ниже. Возможно, они необязательны.
Но этот пункт обсуждаем, лишних тестов не бывает, всё-таки :)

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +				.WithMessage("precision must be a non-negative number less or equal than precision");
К слову, если уж мы хотим жёстко фиксировать сообщение в тесте, то можно было вынести его в аргументы функции, и убрать дублирование кода с предыдущим методом.

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void IsValidNumber_WhenReturnTrue(int precision, int scale, bool onlyPositive, string value)
У аттрибута `[TestCase]` есть параметр "Expected Result". 
Возможно, это как-то поможет избавиться от дублирования с методом ниже?

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
>  		private readonly Regex numberRegex;
Предлагаю внимательно посмотреть на регексп, и проверить, все ли случаи покрываются тестами.
Можешь их тут перечислить, чтобы мы точно ничего не потеряли)

2021-10-30 17:57 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(5, 2, true, "0.000", TestName = "FracPart more scale")]
Не хватает теста на краевой случай, когда `IntPart = Precision`, и при этом ещё указан знак.
Добавишь?

2021-10-30 18:03 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
>  	public class NumberValidatorTests
И в целом мелкое замечание, которое имеет слабое отношение конкретно к этой домашке.

Почти всегда лучше придерживаться композиции 1 класс - 1 файл.
По классам и иерархии легче читать, и быстрее искать нужную инфу в проекте.

А сами тесты обычно вообще выносят в отдельную сборку, чтобы случайно не зареференсить какой-то класс, созданный чисто для тестов, и тем более чтобы они не торчали наружу, если кто-то подключает твой код как библиотеку.

2021-10-30 18:03 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
>  	public class NumberValidatorTests
Можешь разделить, можешь не делить, здесь это не так критично, но в будущих домашках обращай на это внимание

2021-10-30 18:07 UTC, makspanshin commented on cs/HomeExercises/ObjectComparison.cs
> +			actualTsar.Should().BeEquivalentTo(expectedTsar, options => options.AllowingInfiniteRecursion()
Согласно документации по умолчанию рекурсия до 10 лвл.  Если родословное дерево будет содержать больше 10 объектов, то тест будет не корректным. Перемудрил ли я ?

2021-10-30 18:35 UTC, makspanshin commented on cs/HomeExercises/ObjectComparison.cs
> +				.Excluding(member => member.SelectedMemberInfo.Name == "Id"));
Поле `Id` класса ` Pet` будет игнорироваться при сравнении

2021-10-30 18:41 UTC, makspanshin commented on cs/HomeExercises/NumberValidatorTests.cs
> +				.WithMessage("precision must be a positive number");
Так как этот метод тестирует именно исключение связанное с precision(а у него как раз уникальное сообщение). То думаю да, чтобы не словить исключение связанное с другим случаем.

2021-10-30 20:09 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
> +				.Excluding(member => member.SelectedMemberInfo.Name == "Id"));
Это может быть не всегда желаемым поведением.
Давай тоже пофиксим?

Да, если нужно будет заигнорить - придётся доработать этот тест.
Но это будет более явно и безопаснее.

2021-10-30 20:13 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
> +			actualTsar.Should().BeEquivalentTo(expectedTsar, options => options.AllowingInfiniteRecursion()
В целом, ты прав, тест будет некорректным, если такой объект появится.

С другой стороны, представь что у тебя одна Person ссылается на другую и наоборот. Появляется циклическая зависимость.
Можно тут же в настройках указать, чтобы такие зависимости игнорировались, и обойти эту проблему.

Но я предлагаю убрать таймаут и рекурсию по простой причине: в тестах у тебя не будет родословная больше 10 объектов (вероятно, для проверки функциональности тебе хватит глубины 2-3-4).

А вот опасность бесконечной рекурсии и таймаутов - уже не так прикольно. Тесты будут выполняться дольше.
Да и довольно странно: тест не требует никаких вычислений, не общается с внешним миром, нет асинхронности, а таймаут есть.

Твоя задача тут всё же не написать идеальный Equals, а написать тест. Для теста глубины 10 более чем достаточно.

2021-10-30 20:15 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +				.WithMessage("precision must be a positive number");
Принято.

В данном случае, возможно, это оправданно.

2021-10-31 07:41 UTC, makspanshin commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void InitNumberValidator_Сorrectly(int precision, int scale, bool onlyPositive)
Согласен конструктор неявно проверяется тестах ниже. Но у нас в конструкторе заложена логика проверки параметров, поэтому считаю его бы тоже явно проверить. Да еще у нас повышается процент покрытие тестами кода :)

Я бы еще в программах проверял конструктор по умолчанию, на всякий случай. Если в будущем конструктор изменится, упавший тест будет сигнализировать об этом. 

Итог: Я считаю тестировать конструкторы - good idea :)

2021-10-31 07:47 UTC, makspanshin commented on cs/HomeExercises/NumberValidatorTests.cs
>  		private readonly Regex numberRegex;
`numberRegex.Match(value)` может выдать исключение `RegexMatchTimeoutException` , стоит проверить, что время выполнения метода не превышает интервал времени ожидания

2021-10-31 08:11 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
>  		private readonly Regex numberRegex;
Я имел в виду немного не это.
Думаю, что таймаут - не наш случай (это прям постараться нужно, чтобы регексп с таймаутом уронить), предлагаю тесты на это не писать :)

А вот то, что в регекспе есть не только точки, но и запятые, кажется, важно.
Посмотри внимательно на само выражение, может быть ещё что-то есть. (А может и нету :) )

2021-10-31 08:15 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void InitNumberValidator_Сorrectly(int precision, int scale, bool onlyPositive)
Протестировать можно, да.

Минус такой, что если потом захочется в конструктор параметр добавить, его в тестах везде прокидывать придётся.

А пользы-то не сильно много: мы бы и так узнали о проблемах после изменения кода, ведь у нас этот конструктор используется и в тестах ниже.

Но иногда уместно.

Хочешь оставить - давай оставим.
Только нейминги надо улучшить, чтобы точно было понятно всё из названия)

2021-10-31 08:52 UTC, makspanshin commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void IsValidNumber_WhenReturnTrue(int precision, int scale, bool onlyPositive, string value)
Можно эти методы объединить, вот так `return  new NumberValidator(precision, scale, onlyPositive).IsValidNumber(value);` А в названии теста прописать что должно вернуться

2021-10-31 08:55 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void IsValidNumber_WhenReturnTrue(int precision, int scale, bool onlyPositive, string value)
Да, думаю, так будет чище.

Можешь сразу все фиксы пушить, если каких-то вопросов нет конкретных по ним.
Мои вопросы скорее риторические :)

2021-10-31 09:38 UTC, makspanshin commented on cs/HomeExercises/ObjectComparison.cs
Цель этой переменной присвоить объекту уникальное значение, чтобы различать объекты. Первым решением приходит: использовать `Guid` . Можно еще попробовать временные метки Unix в микросекундах. Но `Guid` гораздо лучше выглядит. И тогда мы избавимся от статического поля

2021-10-31 10:22 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
Да, можно так, будет действительно лучше.

Я на самом деле просто обратил внимание на то, что она почему-то публичная, хотя её по-хорошему видеть никто не должен :)

2021-10-31 11:52 UTC, HolyPrapor approved these changes

2021-10-31 11:52 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
> +				                     member.SelectedMemberInfo.DeclaringType.Name =="Person"));
Тут бы как раз кстати пригодился оператор `nameof`. Сейчас если кто-то решит переименовать класс, то и тест фиксить надо будет.
А с `nameof` такого не произойдёт.

2021-10-31 11:52 UTC, HolyPrapor commented on cs/UnitTestNumberValidator/NumberValidatorTests.cs
> +		[TestCase(17, 2, true, "0.0", ExpectedResult = true, TestName = "Input fractional number. Be True")]
Тут конечно можно ещё добавить несколько тестов для запятой. (Со знаком, без знака, негативная.)

Но давай опустим это)

2021-10-31 11:52 UTC, HolyPrapor commented on cs/UnitTestNumberValidator/NumberValidatorTests.cs
> +		public void Init_Сorrectly(int precision, int scale, bool onlyPositive)
Чтобы было понятнее, тут лучше было написано `Init_ShouldNotThrowWhen`.
Тогда бы ещё была связь с прошлым тестом понятная :)

2021-10-31 11:52 UTC, HolyPrapor commented on cs/UnitTestNumberValidator/NumberValidatorTests.cs
> +		[TestCase(2, -1, true, "precision must be a non-negative number less or equal than precision",
Текст, чтобы не дублировать, можно было вынести в константу, но это уже супер придирки)

2021-10-31 11:52 UTC, HolyPrapor commented on cs/UnitTestNumberValidator/NumberValidatorTests.cs
> +		public bool IsValidNumber_Test(int precision, int scale, bool onlyPositive, string value)
Я бы выбрал такой паттерн, чтобы было `IsValidNumber_When.Input double dot. Should be false`.
Мне кажется, что так проще читается.

2021-10-31 11:52 UTC, HolyPrapor commented on cs/UnitTestNumberValidator/NumberValidatorTests.cs
> +			return  new NumberValidator(precision, scale, onlyPositive).IsValidNumber(value);
Тут два пробела между `return` и `new`.
Не забывай форматировать, дело пары кнопок)

2022-10-26 20:04 UTC, closed without merging