Первый запрос на код-ревью по ДЗ Testing
kontur-courses/testing pull request #159
Opened 2021-10-31 12:58 UTC by SlavikGh0st

2021-11-01 03:30 UTC, bannikovilea requested changes

2021-11-01 03:30 UTC, bannikovilea commented on cs/HomeExercises/ObjectComparison.cs
> +										 .Excluding(ctx => ctx.SelectedMemberPath.EndsWith("Parent.Id")));
В самом классе поле могут переименовать и тест станет невалидным, было бы классно заиспользовать, например `nameof(Person.Parent.Id))`, так как при рефакторинге поля имя в тесте тоже порефакторится

2021-11-01 05:41 UTC, SlavikGh0st commented on cs/HomeExercises/ObjectComparison.cs
> +
> Конечно, этот код был дан, и его менять не предполагалось, но всегда полезно смотреть по сторонам и предлагать улучшения, если они возможны)

Я просто не знал, насколько в данном задании даётся свободы для исправления кода, поэтому чётко следовал инструкциям)

> Давай погрузимся до кода в классе `Person`. Предлагаю подумать над тем, логично ли, что там есть какая-то публичная статическая переменная `IdCounter`, и можно ли как-то сделать лучше?

Есть 2 варианта:
1) Сделать это поле закрытым (private, protected), если мы очень хотим, чтобы Id оставался целочисленным и автоинкрементируемым. Таким образом, никто извне не сможет вмешаться в логику работы класса.
2) Мы можем отказаться от целочисленного Id и сделать что-то вроде public Guid Id { get; }, а при создании экземпляра в конструкторе будет отрабатываться Id = Guid.NewGuid();

> Предлагаю `Person` и `Registry` вынести в отдельные файлы

Ок, исправим.

2021-11-01 05:45 UTC, SlavikGh0st commented on cs/HomeExercises/ObjectComparison.cs
> +										 .Excluding(ctx => ctx.SelectedMemberPath.EndsWith("Parent.Id")));
> было бы классно заиспользовать, например `nameof(Person.Parent.Id))`

Согласен, как-то забыл про этот момент

2021-11-01 05:49 UTC, SlavikGh0st commented on cs/Samples/Antipatterns/Stack3_Tests.cs
>  			var stack = new Stack<int>();
Это пример тестов-антипаттернов, который входил в курс обучения и был специально подготовлен программистами Контура. Он должен оставаться плохим, чтобы мы в любой момент могли посмотреть, как не стоит писать тесты)

2021-11-01 05:59 UTC, SlavikGh0st commented on cs/Challenge/WordsStatistics_Tests.cs
> +		public void AddWord_ShouldWorkOnSecond_IfAddLotOfSameWords()
Данные тесты были созданы во время практики, которая проходила в виде соревнования. У нас была обновляемая таблица, куда выводилась информация о команде, о том, какие тесты решены, какие ещё нет, какие решены повторно (избыточные тесты).
Комментированием кода мы определяли, является ли тест избыточным или нет)

2021-11-01 06:08 UTC, SlavikGh0st commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void NumberValidator_CorrectArguments_DoesNotThrowException(int precision, int scale = 0, bool onlyPositive = false)
Писал тест, который бы полностью повторял сигнатуру конструктора и даже пока не задумывался об этом, что это может быть лишним.
С другой стороны, мы можем быстро добавить ещё пару тест-кейсов типа '[TestCase(1)]', '[TestCase(1,0)]', и быть уверенными, что такое количество аргументов работает исправно)

2021-11-01 06:09 UTC, SlavikGh0st commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void IsValidNumber_CorrectCase_ShouldReturnTrue(string value, int precision, int scale = 0, bool onlyPositive = false)
> Предлагаю поизучать аттрибут `TestCaseSource` и вынести схожие тестКейзы в один источник

Ок, изучим-попробуем.

2021-11-02 02:15 UTC, bannikovilea commented on cs/Challenge/WordsStatistics_Tests.cs
> +		public void AddWord_ShouldWorkOnSecond_IfAddLotOfSameWords()
Ага) 
В зачет домашки не пойдет - а для общего развития, думаю полезно)

2021-11-02 02:29 UTC, bannikovilea commented on cs/HomeExercises/ObjectComparison.cs
> +
>Я просто не знал, насколько в данном задании даётся свободы для исправления кода, поэтому чётко следовал инструкциям)

Смотреть по сторонам всегда полезно) Задавать вопросы - почему так сделано и можно ли это улучшить - хороший подход. Про такое, например, могли просто забыть, и то, что ты обратил внимание сделает лучше. А может тебе расскажут почему это тут и работает именно так  и ты получишь новое знание)

2021-11-02 07:15 UTC, bannikovilea commented on cs/HomeExercises/ObjectComparison.cs
> +
> Есть 2 варианта:

Оба варианта имеют право на существование, но лично мне больше нравится второй с Guid) Так как вероятность наловить коллизий на ИдКаунтера тут минимальная

2021-11-02 10:52 UTC, bannikovilea commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void NumberValidator_CorrectArguments_DoesNotThrowException(int precision, int scale = 0, bool onlyPositive = false)
Предлагаю убрать их, пока такие тесты не появятся)

2021-11-03 04:25 UTC, bannikovilea commented
После ревью @SlavikGh0st  остались очень приятные ощущения т.к.

- изменения разбиты на коммиты
- дух задания понят правильно
- в целом довольно приятно читать код
- правки вносились оперативно
- вопросы были интересные и по делу

Так и держать дальше 👍)
Удачи со следующим заданием!

2021-11-03 04:25 UTC, closed without merging