Homework_1
kontur-courses/testing pull request #160
Opened 2021-10-31 13:14 UTC by SlivnyiArtem

2021-10-31 15:16 UTC, lamanoff requested changes

2021-10-31 15:16 UTC, lamanoff commented on cs/HomeExercises/NumberValidatorTests.cs
> +		//БЫЛО
Не все повторы были найдены.

2021-10-31 15:16 UTC, lamanoff commented on cs/HomeExercises/NumberValidatorTests.cs
> +		//БЫЛО
Каких проверок не хватает?

2021-10-31 15:16 UTC, lamanoff commented on cs/HomeExercises/NumberValidatorTests.cs
> +//Старые варианты тестов(Просто, чтобы не потерять)))))))
Можно было перенести их в отдельный файлик или удалить, если они не нужны для решения.

2021-10-31 15:16 UTC, lamanoff commented on cs/HomeExercises/ObjectComparison.cs
> +			actualTsar.Should().BeEquivalentTo(expectedTsar, options => options.Excluding(tsar => tsar.Id).Excluding(tsar=> tsar.Parent.Id));
А что будем делать с родителями родителей и их родителями?)

2021-10-31 15:16 UTC, lamanoff commented on cs/HomeExercises/ObjectComparison.cs
> +			actualTsar.Should().BeEquivalentTo(expectedTsar, options => options.Excluding(tsar => tsar.Id).Excluding(tsar=> tsar.Parent.Id));
Можно улучшить читаемость перенося строки.

2021-10-31 15:16 UTC, lamanoff commented on cs/HomeExercises/ObjectComparison.cs
> +		public Person(string name, int age, int height, int weight, Person? parent)
Добавился пробел в конце строки) В настройках IDE можно включить настройку, которая будет удалять лишние пробелы про сохранении файла.

2021-10-31 15:48 UTC, SlivnyiArtem commented on cs/HomeExercises/NumberValidatorTests.cs
> +		readonly string valid = " is valid number for NumberValidator";
Да, согласен, "артефакт" изменения. В самом конце решил свести повторяющийся код в один метод, до этого в полях был смысл)

2021-10-31 15:48 UTC, SlivnyiArtem commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void TestConstructor()
Ок, разобью

2021-10-31 15:48 UTC, SlivnyiArtem commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void TestConstructor()
И переименую)))

2021-10-31 15:50 UTC, SlivnyiArtem commented on cs/HomeExercises/NumberValidatorTests.cs
> +//Старые варианты тестов(Просто, чтобы не потерять)))))))
Понял, сейчас они у меня в более старых коммитах)))

2021-11-02 10:07 UTC, lamanoff requested changes

2021-11-02 10:07 UTC, lamanoff commented on cs/HomeExercises/NumberValidatorTests.cs
> +				" and\n because the format of a numeric value " +
Вместо `because` можно использовать `TestName`, в котором указывать требуемое поведение. Тогда тест будет читаться легче и каждый кейс будет понятен.

2021-11-02 10:07 UTC, lamanoff commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void ShouldThrowExceptionWhenScaleIsGreaterThenPrecision()
Следует ставить землю (`_`) перед словом `When`, тогда будет более читаемо.

2021-11-02 10:07 UTC, lamanoff commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void ShouldThrowExceptionWhenPrecisionIsNotPositive2()
Эти тесты явно можно определить под тест кейсами.

2022-10-26 20:04 UTC, closed without merging