Арсений Карпов
kontur-courses/testing pull request #170
Opened 2021-11-01 19:33 UTC by jexinox

@vormanov
С коммитами беда, конечно...

2021-11-02 11:27 UTC, vormanov requested changes

2021-11-02 11:27 UTC, vormanov commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(1, 1, TestName = "With scale equals precision")]
Тут просто отступ съехал)

2021-11-02 11:27 UTC, vormanov commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(10, 5, true, "-1.23", ExpectedResult = false, TestName = "With minus when onlyPositive")]
У этого теста набор тестовых кейсов, по сути, аналогичен кейсам в тесте `NumberValidator_ConstructorDoesNotThrows`. Предлагаю поизучать атрибут `TestCaseSource` и объединить эти кейсы в метод-генератор и передать его в `TestCaseSource` у этих тестов вместо `TestCase`.

2021-11-02 11:27 UTC, vormanov commented on cs/HomeExercises/NumberValidatorTests.cs
> +			return validator.IsValidNumber(num);
Думаю, что тут лучше тоже использовать FluentAssertions вместо булевого теста, будет нагляднее, какое поведение ожидается и единообразная структура тестов "подготовительные операции(если нужно) - выполнение тестируемых операций - проверка результата".

2021-11-02 11:27 UTC, vormanov commented on cs/HomeExercises/ObjectComparison.cs
> +		public static int IdCounter;
А почему решил убрать явное определение счетчика? Мне кажется, оно помогает быстро и однозначно понять стартовое значение счетчика.
Тут, скорее, можно сделать этот счетчик приватным, незачем в данном случае к нему снаружи доступ иметь.

2021-11-02 11:27 UTC, vormanov commented on cs/HomeExercises/ObjectComparison.cs
> +					member.SelectedMemberInfo.Name == "Id"));
Тут все супер, просто совет для наглядности указывать поле не строкой, а через `nameof(Person.Id)`. 
Да и если это поле будет удалено или переименовано этот тест просто не соберется вместо некорректной работы и его точно не забудут доработать.

2021-11-02 11:39 UTC, jexinox commented on cs/HomeExercises/ObjectComparison.cs
> +		public static int IdCounter;
Да, я тоже считаю, что явное указание будет лучше, просто resharper'у почему-то очень не понравилось и глаза мозолил, нужно отключить просто было эту ошибку)

2021-11-02 11:41 UTC, jexinox commented on cs/HomeExercises/NumberValidatorTests.cs
> +			return validator.IsValidNumber(num);
Получается лучше разбить на два метода, когда должно быть True и когда false?

2021-11-02 13:32 UTC, vormanov commented on cs/HomeExercises/NumberValidatorTests.cs
> +			return validator.IsValidNumber(num);
На самом деле в зависимости от ситуации могут применяться оба подхода, но тут задача довольно общая, поэтому давай в данном случае на 2 теста поделим.

2021-11-02 14:07 UTC, vormanov commented on cs/HomeExercises/NumberValidatorTests.cs
> +			return validator.IsValidNumber(num);
Тогда можно сделать отдельные методы с `TestCaseSource` для теста на True и False, а в тесте конструктора взять их обоих.

2021-11-03 07:56 UTC, jexinox commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(10, 5, true, "-1.23", ExpectedResult = false, TestName = "With minus when onlyPositive")]
Смотри, а там же я еще передаю параметр num для .IsValidNumber, в конструкторе мне его не надо принимать, как эту проблему можно решить?

2021-11-03 09:02 UTC, vormanov commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(10, 5, true, "-1.23", ExpectedResult = false, TestName = "With minus when onlyPositive")]
Да, есть у этого подхода такой нюанс, что в случае с конструктором один параметр тест не будет брать на вход, но зато большим плюсом является то, что при добавлении кейсов в тесты, они точно добавятся во все, в которые надо и ничего не забудется.

2022-10-26 20:04 UTC, closed without merging