Суримов Максим
kontur-courses/testing pull request #172
Opened 2021-11-03 14:51 UTC by MaxxLorge

@HolyPrapor

2021-11-03 16:02 UTC, HolyPrapor requested changes

2021-11-03 16:02 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
>  {
Можешь разделить, можешь не делить, здесь это не так критично, но в будущих домашках обращай на это внимание

2021-11-03 16:02 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void ShouldNotThrowException_WithCorrectParametersInConstructor(int precision, int scale,
Как думаешь, действительно ли нужны отдельные тесты на работающий конструктор?

Кажется, что эти тесты "неявно" проходятся в тестах ниже. И если что-то падает, то мы узнаем там.

2021-11-03 17:52 UTC, MaxxLorge commented on cs/HomeExercises/NumberValidatorTests.cs
> +			nv.IsValidNumber(number).Should().BeFalse();
Просто так потеряется семантика названия. Сейчас у меня два метода: первый - там где валидация успешна, второй - где нет. Получается, что один метод будет отвечать за оба случая.

2021-11-03 18:01 UTC, MaxxLorge commented on cs/HomeExercises/NumberValidatorTests.cs
> -			numberRegex = new Regex(@"^([+-]?)(\d+)([.,](\d+))?$", RegexOptions.IgnoreCase);
Не могу придумать, разве что можно протестить случаи с экзотическими разделителями или знаками в начале.

2021-11-03 18:02 UTC, MaxxLorge commented on cs/HomeExercises/NumberValidatorTests.cs
> +public class NumberValidator
Даже как-то не знаю, внес обратно)

2021-11-03 18:04 UTC, MaxxLorge commented on cs/HomeExercises/NumberValidatorTests.cs
> +		[TestCase(4, 2, true, "+1.23", TestName = "+1.23 dot separated with precision=4 and scale=2")]
Такие уже были, но еще один добавил.
precision doesn't allow more digit и precision doesn't allow sign

2021-11-03 18:15 UTC, MaxxLorge commented on cs/HomeExercises/ObjectComparison.cs
> +				.Excluding(p => p.SelectedMemberInfo.Name == "Id"));
Исправил

2021-11-03 18:22 UTC, MaxxLorge commented on cs/HomeExercises/ObjectComparison.cs
> +		public static int IdCounter;
В данном случае не вижу особого смысла в этом поле, в нашем случае приходится отдельно указывать, чтобы это поле игнорировалось, так как при создании нового объекта id инкрементируется, даже если по смыслу объекты равны. Даже если необходимо было подобное поле, то лучше, на мой взгляд, воспользоваться более подходящими средствами, например, Guid.

2021-11-03 18:23 UTC, MaxxLorge commented on cs/HomeExercises/ObjectComparison.cs
> +		public static int IdCounter;
Даже если оставить int, то поле IdCounter можно было сделать приватным.

2021-11-03 18:25 UTC, MaxxLorge commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void ShouldNotThrowException_WithCorrectParametersInConstructor(int precision, int scale,
Думаю, что эти тесты действительно можно убрать.

2021-11-03 18:40 UTC, MaxxLorge commented on cs/HomeExercises/ObjectComparison.cs
> +				.Excluding(p => p.SelectedMemberInfo.Name == "Id"));
Это поле будет игнорироваться тестом.

2021-11-03 18:47 UTC, MaxxLorge commented on cs/HomeExercises/ObjectComparison.cs
> +				.Excluding(p => p.SelectedMemberInfo.Name == "Id"));
Исправил это поведение

2021-11-03 20:56 UTC, MaxxLorge commented on cs/HomeExercises/NumberValidatorTests.cs
> +		public void ShouldBeValid(int precision, int scale, bool onlyPositive, string number)
Выбрал предложенный вариант и переименовал на этот лад. Так действительно выглядит лучше, плюс понятно, какой кейс тестируется, а точные данные можно посмотреть при желании в атрибуте.

2021-11-04 06:33 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> +			nv.IsValidNumber(number).Should().BeFalse();
Принято, можем оставить так.

Можно поизвращаться и придумать название, которое бы подходило под оба случая, но дублирования тут практически нету, так что опустим это

2021-11-04 06:34 UTC, HolyPrapor commented on cs/HomeExercises/NumberValidatorTests.cs
> -			numberRegex = new Regex(@"^([+-]?)(\d+)([.,](\d+))?$", RegexOptions.IgnoreCase);
Я имел в виду случаи с запятой (положительное со знаком, положительное без знака, отрицательное). В общем, всё что уже написано, только ещё и для запятой.

Но давай тоже опустим это

2021-11-04 06:35 UTC, HolyPrapor commented on cs/HomeExercises/ObjectComparison.cs
> +		public static int IdCounter;
`Guid`, конечно, более уместен для уникальных объектов. Но такой дёшевый хак тоже неплох.

Но да, я имел в виду просто сделать переменную приватной)

2021-11-04 06:37 UTC, HolyPrapor approved these changes
LGTM!
Great job!

2022-10-26 20:04 UTC, closed without merging