Вашурин Артем
kontur-courses/testing pull request #185
Opened 2022-10-29 14:25 UTC by ArtAkaArt

@coffee_and_problems

2022-11-01 15:22 UTC, coffee-and-problems requested changes
Молодец, что оставил комментарии к неочевидным местам, которые зацепили твое внимание)
Все изменения ты изначально сделал в одном коммите и назвал его Solution. Давай порассуждаем, хороший ли это коммит? Легко ли будет тебе откатить часть изменений? Легко ли будет другому разработчику (или тебе через месяц) понять, что могло измениться в коде в этом коммите?

2022-11-01 15:22 UTC, coffee-and-problems commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(1, 0, true, "1", ExpectedResult = true, TestName = "Integer whithout sign")]
А тут ExpectedResult на что-то влияет? Почему он всегда true? Можно ли его вообще не писать в параметрах?

2022-11-01 15:22 UTC, coffee-and-problems commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(2, 0, true, "+1", ExpectedResult = true, TestName = "Positive integer")]
Давай еще подумаем, можно ли этот тест разделить на несколько и по какой логике?

2022-11-01 15:22 UTC, coffee-and-problems commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(3, 0, true, "1..1", ExpectedResult = false, TestName = "Decimal with same double separator")]
К комменту выше про разделение теста: один из разделенных тестов, возможно, захочется сгруппировать с кейсами отсюда

2022-11-01 15:25 UTC, coffee-and-problems commented on cs/HomeExercises/ObjectComparison.cs
> +				.Excluding(p => p.Parent!.Weight) // в оригинале нет теста для weight
Речь о весе родителя, такой проверки действительно нет

2022-11-01 16:05 UTC, ArtAkaArt commented on cs/HomeExercises/ObjectComparison.cs
> +			//Assert.AreEqual(expectedTsar.Parent.Parent, actualTsar.Parent.Parent); - сравнивает ссылки
> Но тут я бы задалась вопросом, а корректно ли это с точки зрения логики?

Я так понимаю, автор оригинального теста просто хотел остановиться в сравнении вложенных объектов в каком-то месте. А то писать тесты для сравнения их полей вручную можно было бы до бесконечности. Поэтому я не думаю что это именно баг =)
Но с точки зрения логики теста, это да, странно выглядит =)

2022-11-01 16:07 UTC, ArtAkaArt commented on cs/HomeExercises/ObjectComparison.cs
> +				.Excluding(p => p.Parent!.Weight) // в оригинале нет теста для weight
Увы :) (строки 25+)
![image](https://user-images.githubusercontent.com/91897648/199280667-fd3fcbb4-46b1-43c0-b10c-0231509fbb91.png)

2022-11-01 17:37 UTC, ArtAkaArt commented
С nameof не очень получается, он просто возвращает строку "Id", которую можно и так написать. 
Но тут главная проблема, что в старой версии Fluent Assertsions не получается проверять путь поля. Поэтому оставил новую в раках этого задания (хоть это и влечет вышеупомянутую проблему), просто чтобы показать, как на мой взгляд мог бы такой тест выглядеть =)

2022-11-01 17:46 UTC, ArtAkaArt commented on cs/HomeExercises/ObjectComparison.cs
> +			// 3 проверка сильно привязана к структуре объекта
Тест выше, который переписан с Fluent Assertsions только исключает некоторые поля и добавление новых полей в объект Person не исключит их из такой проверки.
В то время как тест CheckCurrentTsar_WithCustomEquality, будет проверять только те поля, которые прописаны в методе AreEqual.

2022-11-01 17:52 UTC, ArtAkaArt commented on cs/HomeExercises/ObjectComparison.cs
> +			// равны объекты или нет, а проверить соответствует ли объект заданным параметрам и => всего 1 assert
Тут я имел в виду, что assert как таковой не дает детальной информации и том, где тест не прошел проверку.
Если переписать такой тест с и разбить его на несколько ассертов, то можно будет хотя бы увидеть номер строки какой именно ассерт и => какой именно параметр не прошел проверки.

2022-11-01 18:14 UTC, ArtAkaArt commented on cs/HomeExercises/NumberValidatorTests.cs
> +        [TestCase(0, 0, true)]
Блин! Не заметил, что есть значение по умолчанию =(

2022-11-02 05:02 UTC, coffee-and-problems commented on cs/HomeExercises/ObjectComparison.cs
> +			// 3 проверка сильно привязана к структуре объекта
Ага, это правильно

2022-11-02 05:06 UTC, coffee-and-problems commented
> С nameof не очень получается, он просто возвращает строку "Id", которую можно и так написать.

А в чем отличие захардкоженной строки "Id" от получения ее через nameof? Подсказка: в какой момент будет вычисляться значение?

2022-11-02 08:16 UTC, coffee-and-problems commented on cs/HomeExercises/ObjectComparison.cs
> +			//Assert.AreEqual(expectedTsar.Parent.Parent, actualTsar.Parent.Parent); - сравнивает ссылки
Не факт, что автор оригинального теста именно этого хотел, он мог просто по неопытности ошибиться. Лучше не предполагать намерения программистов из прошлого, а руководствоваться логикой - теперь это твой код, тебе его развивать и поддерживать

2022-11-02 08:38 UTC, ArtAkaArt commented on cs/HomeExercises/ObjectComparison.cs
> +			//Assert.AreEqual(expectedTsar.Parent.Parent, actualTsar.Parent.Parent); - сравнивает ссылки
Не думаю, что это ошибка, в тестах входные данные предполагают сравнение ссылок Preson.Parent.Parent, а не их значений:
![image](https://user-images.githubusercontent.com/91897648/199440115-940e187c-ad63-4a0d-8002-aa1dbdfbc299.png)

2023-11-23 04:54 UTC, closed without merging